// packages/react/src/components/localess-document.tsx
import {forwardRef, useEffect, useState} from "react";
import {ContentData, isBrowser, Links, References} from "@localess/client";
import {LocalessComponent} from "./localess-component";
import {isSyncEnabled} from "../state";

export type LocalessDocumentProps<T extends ContentData = ContentData> = {
  data: T
  links?: Links
  references?: References;
}

export const LocalessDocument = forwardRef<HTMLElement, LocalessDocumentProps>(({data, links, references, ...restProps}, ref) => {
  const [contentData, setContentData] = useState(data);
  useEffect(() => {
    if (isSyncEnabled() && isBrowser()) {
      window.localess?.on(['input', 'change'], (event) => {
        console.log('Localess:event', event)
        if (event.type === 'change' || event.type === 'input') {
          setContentData(event.data)
        }
      })
    }
  })

  return (
    <LocalessComponent data={contentData} links={links} references={references} {...restProps}/>
  );
});

// packages/svelte/src/lib/components/LocalessDocument.svelte
<script lang="ts" generics="T extends ContentData = ContentData">
  import { untrack } from 'svelte';

  import { FONT_BOLD, FONT_NORMAL } from '../console';
  import { localessSyncOnChange } from '../core/state';
  import LocalessComponent from './LocalessComponent.svelte';
  import type { LocalessDocumentProps, ContentData } from '../models';

  let { document }: LocalessDocumentProps<T> = $props();

  let contentData = $state(untrack(() => document.data));

  $effect(() => {
    if (!contentData) {
      console.error('LocalessDocument property %cdocument.data%c is not provided.', FONT_BOLD, FONT_NORMAL);
    }
  });

  $effect(() => {
    localessSyncOnChange(event => {
      contentData = event.data;
    });
  });
</script>

{#if contentData}
  <LocalessComponent data={contentData} assets={document.assets} links={document.links} references={document.references} />
{:else}
  <p>LocalessDocument property <b>document.data</b> is not provided.</p>
{/if}
