// packages/react/src/components/localess-component.tsx
import {forwardRef} from "react";
import {ContentData, Links, localessEditable, References} from "@localess/client";
import {FONT_BOLD, FONT_NORMAL} from "../console";
import {getComponent, getFallbackComponent, isSyncEnabled} from "../state";

export type LocalessComponentProps<T extends ContentData = ContentData> = {
  data: T
  links?: Links
  references?: References;
}

export const LocalessComponent = forwardRef<HTMLElement, LocalessComponentProps>(({data, links, references, ...restProps}, ref) => {
  if (!data) {
    console.error('LocalessComponent property %cdata%c is not provided.', FONT_BOLD, FONT_NORMAL)
    return <div>LocalessComponent property <b>data</b> is not provided.</div>
  }
  // Find Component from Mapping
  const Comp = getComponent(data._schema);
  if (Comp) {
    const attr = isSyncEnabled() ? localessEditable(data) : {};
    return <Comp ref={ref} data={data} links={links} references={references} {...attr} {...restProps} />;
  }
  // Try to use Fallback Component
  const FallbackComponent = getFallbackComponent()
  if (FallbackComponent) {
    return <FallbackComponent ref={ref} data={data} links={links} references={references} {...restProps} />
  }
  // Missing Configuration case
  return (
    <p>
      <b>LocalessComponent</b> could not found component with key <b>{data._schema || data.schema}</b>. <br/>
      Please check if your configuration is correct.
    </p>
  );
});

// packages/svelte/src/lib/components/LocalessComponent.svelte
<script lang="ts" generics="T extends ContentData = ContentData">
  import { getComponent, getFallbackComponent } from '../client';
  import type { LocalessComponentProps, ContentData} from '../models';
  import {localessEditable} from "$lib/utils";

  let { data, assets, links, references }: LocalessComponentProps<T> = $props();

  let Comp = $derived(getComponent(data._schema));
  let Fallback = $derived(getFallbackComponent());
  let attrs = $derived(localessEditable(data));
</script>

{#if Comp}
  <Comp {data} {assets} {links} {references} {...attrs} />
{:else if Fallback}
  <Fallback {data} {assets} {links} {references} />
{:else}
  <p>LocalessComponent could not find component with key <b>{data._schema}</b>. Please check if your configuration is correct.</p>
{/if}
