// packages/svelte/src/lib/components/LocalessDocument.svelte
<script lang="ts" generics="T extends ContentData = ContentData">
  import { untrack } from 'svelte';

  import { FONT_BOLD, FONT_NORMAL } from '../console';
  import { localessSyncOnChange } from '../client';
  import LocalessComponent from './LocalessComponent.svelte';
  import type { LocalessDocumentProps, ContentData } from '../models';

  let { document }: LocalessDocumentProps<T> = $props();

  let contentData = $state(untrack(() => document.data));

  // Re-syncs whenever the `document` prop itself changes — e.g. client-side navigation to a new
  // slug in SvelteKit reuses this component instance and just updates its props, so without this
  // the previously rendered content would stick even though `document` now points elsewhere.
  $effect(() => {
    contentData = document.data;
  });

  $effect(() => {
    if (!contentData) {
      console.error('LocalessDocument property %cdocument.data%c is not provided.', FONT_BOLD, FONT_NORMAL);
    }
  });

  $effect(() =>
    localessSyncOnChange(event => {
      // The page may render several documents; only this one's edits apply here.
      if (event.documentId === document.id) contentData = event.data;
    })
  );
</script>

{#if contentData}
  <LocalessComponent data={contentData} assets={document.assets} links={document.links} references={document.references} />
{:else}
  <p>LocalessDocument property <b>document.data</b> is not provided.</p>
{/if}

// packages/vue/src/components/localess-document.vue
<script setup lang="ts">
import { onMounted, onScopeDispose, ref, watch, watchEffect } from 'vue';

import { localessSyncOnChange } from '../client';
import { ContentData, LocalessDocumentProps} from '../models';
import LocalessComponent from './localess-component.vue';

defineOptions({ name: 'LocalessDocument' });

const props = defineProps<LocalessDocumentProps>();

const contentData = ref<ContentData | undefined>(props.document.data);

// Re-syncs whenever the `document` prop itself changes — e.g. client-side navigation to a new
// slug in Nuxt reuses this component instance and just updates its props, so without this the
// previously rendered content would stick even though `document` now points elsewhere.
watch(
  () => props.document,
  doc => {
    contentData.value = doc.data;
  }
);

let unsubscribe: (() => void) | undefined;
onMounted(() => {
  unsubscribe = localessSyncOnChange(event => {
    // The page may render several documents; only this one's edits apply here.
    if (event.documentId === props.document.id) contentData.value = event.data;
  });
});
onScopeDispose(() => unsubscribe?.());

watchEffect(() => {
  if (!contentData.value) {
    console.error('LocalessDocument property document.data is not provided.');
  }
});
</script>

<template>
  <LocalessComponent v-if="contentData" :data="contentData" :assets="document.assets" :links="document.links" :references="document.references" />
  <p v-else>LocalessDocument property <b>document.data</b> is not provided.</p>
</template>
