// packages/react/src/core/components/localess-rich-text.tsx
import type { LocalessRichTextInput } from '@localess/richtext';
import React from 'react';

import { type LocalessReactRichTextRenderers, renderRichText } from '../richtext';

export interface LocalessRichTextProps {
  /** The rich text field value (`ContentRichText` / TipTap JSON). */
  content: LocalessRichTextInput;
  /** Optional per-node/per-mark overrides (React components). */
  renderers?: LocalessReactRichTextRenderers;
}

/**
 * Renders a Localess rich text field.
 *
 * @example
 * ```tsx
 * <LocalessRichText content={data.body} />
 * ```
 */
export function LocalessRichText({ content, renderers }: LocalessRichTextProps): React.ReactNode {
  return renderRichText(content, { renderers });
}

// packages/angular/src/components/localess-rich-text.component.ts
import { ChangeDetectionStrategy, Component, computed, inject, input } from '@angular/core';
import { DomSanitizer } from '@angular/platform-browser';
import { type LocalessRichTextInput, type LocalessRichTextRenderers, renderRichTextToHtml } from '@localess/richtext';

/**
 * Renders a Localess rich text field into the host element.
 *
 * @example
 * ```html
 * <ll-rich-text [content]="data.body" />
 * ```
 */
@Component({
  selector: 'll-rich-text',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '',
  host: { '[innerHTML]': 'html()' },
})
export class LocalessRichText {
  private readonly sanitizer = inject(DomSanitizer);

  readonly content = input.required<LocalessRichTextInput>();
  readonly renderers = input<LocalessRichTextRenderers<string>>();

  readonly html = computed(() =>
    this.sanitizer.bypassSecurityTrustHtml(renderRichTextToHtml(this.content(), { renderers: this.renderers() }))
  );
}
