// playgrounds/nuxt/app/components/localess/Page.vue
<script setup lang="ts">
import {LocalessComponent, LocalessRichText, type LocalessSchemaProps, localessEditable, localessEditableField} from '@localess/vue';

import type { Page } from '#shared/models/localess';

const props = defineProps<LocalessSchemaProps<Page>>();
</script>

<template>
  <main v-bind="localessEditable(props.data)" class="flex flex-col gap-4">
    <h1 v-bind="localessEditableField<Page>('title')" class="text-center">{{ props.data.title }}</h1>
    <p v-if="props.data.description" v-bind="localessEditableField<Page>('description')" class="text-center whitespace-pre-line">
      {{ props.data.description }}
    </p>
    <div v-if="props.data.buttons?.length" class="flex justify-center gap-2">
      <LocalessComponent v-for="button in props.data.buttons" :key="button._id" :data="button" />
    </div>
    <div v-if="props.data.content" v-bind="localessEditableField<Page>('content')" class="prose dark:prose-invert mx-auto">
      <LocalessRichText :content="props.data.content" />
    </div>
  </main>
</template>

// playgrounds/svelte-kit/src/lib/components/localess/Page.svelte
<script lang="ts">
  import { LocalessComponent, LocalessRichText, localessEditable, localessEditableField } from '@localess/svelte';

  import type { Page } from '../../../shared/models/localess';

  let { data }: { data: Page } = $props();
</script>

<main use:localessEditable={data} class="flex flex-col gap-4">
  <h1 {...localessEditableField<Page>('title')} class="text-center">{data.title}</h1>
  {#if data.description}
    <p {...localessEditableField<Page>('description')} class="text-center whitespace-pre-line">{data.description}</p>
  {/if}
  {#if data.buttons?.length}
    <div class="flex justify-center gap-2">
      {#each data.buttons as button (button._id)}
        <LocalessComponent data={button} />
      {/each}
    </div>
  {/if}
  {#if data.content}
    <div {...localessEditableField<Page>('content')} class="prose dark:prose-invert mx-auto">
      <LocalessRichText content={data.content} />
    </div>
  {/if}
</main>
