// packages/react/src/ssr/localess-component.tsx
import {forwardRef} from "react";
import {FONT_BOLD, FONT_NORMAL} from "../console";
import {getComponent, getFallbackComponent} from "../core/state";
import {ContentData, Links, References} from "../core/models";

export type LocalessServerComponentProps<T extends ContentData = ContentData> = {
  data: T
  links?: Links
  references?: References;
}

export const LocalessServerComponent = forwardRef<HTMLElement, LocalessServerComponentProps>(({data, links, references, ...restProps}, ref) => {
  if (!data) {
    console.error('LocalessServerComponent property %cdata%c is not provided.', FONT_BOLD, FONT_NORMAL)
    return <div>LocalessServerComponent property <b>data</b> is not provided.</div>
  }
  // Find Component from Mapping
  const Comp = getComponent(data._schema);
  if (Comp) {
    return <Comp ref={ref} data={data} links={links} references={references} {...restProps} />;
  }
  // Try to use Fallback Component
  const FallbackComponent = getFallbackComponent()
  if (FallbackComponent) {
    return <FallbackComponent ref={ref} data={data} links={links} references={references} {...restProps} />
  }
  // Missing Configuration case
  return (
    <p>
      <b>LocalessServerComponent</b> could not found component with key <b>{data._schema}</b>. <br/>
      Please check if your configuration is correct.
    </p>
  );
});

// packages/svelte/src/lib/LocalessComponent.svelte
<script lang="ts">
  import { getComponent, getFallbackComponent } from './core/state';
  import { localessEditable, type Assets, type ContentDataSchema, type Links, type References } from './models';

  let { data, assets, links, references }: { data: ContentDataSchema; assets?: Assets; links?: Links; references?: References } =
    $props();

  let Comp = $derived(getComponent(data._schema));
  let Fallback = $derived(getFallbackComponent());
  let attrs = $derived(localessEditable(data));
</script>

{#if Comp}
  <Comp {data} {assets} {links} {references} {...attrs} />
{:else if Fallback}
  <Fallback {data} {assets} {links} {references} />
{:else}
  <p>LocalessComponent could not find component with key <b>{data._schema}</b>. Please check if your configuration is correct.</p>
{/if}
