// packages/vue/src/components/localess-component.vue
<script setup lang="ts">
import { computed } from 'vue';

import { getComponent, getFallbackComponent } from '../client';
import { LocalessComponentProps } from '../models';
import { localessEditable } from '../utils';

defineOptions({ name: 'LocalessComponent' });

const props = defineProps<LocalessComponentProps>();

const resolved = computed(() => getComponent(props.data._schema));
const fallback = computed(() => getFallbackComponent());
</script>

<template>
  <component :is="resolved" v-if="resolved" :data="data" :assets="assets" :links="links" :references="references" v-bind="localessEditable(data)" />
  <component :is="fallback" v-else-if="fallback" :data="data" :assets="assets" :links="links" :references="references" />
  <p v-else>LocalessComponent could not find component with key <b>{{ data._schema }}</b>. Please check if your configuration is correct.</p>
</template>

// packages/svelte/src/lib/LocalessComponent.svelte
<script lang="ts">
  import { getComponent, getFallbackComponent } from './core/state';
  import { localessEditable, type Assets, type ContentDataSchema, type Links, type References } from './models';

  let { data, assets, links, references }: { data: ContentDataSchema; assets?: Assets; links?: Links; references?: References } =
    $props();

  let Comp = $derived(getComponent(data._schema));
  let Fallback = $derived(getFallbackComponent());
  let attrs = $derived(localessEditable(data));
</script>

{#if Comp}
  <Comp {data} {assets} {links} {references} {...attrs} />
{:else if Fallback}
  <Fallback {data} {assets} {links} {references} />
{:else}
  <p>LocalessComponent could not find component with key <b>{data._schema}</b>. Please check if your configuration is correct.</p>
{/if}
